"""first

Revision ID: 29654331bd83
Revises: 
Create Date: 2025-12-14 14:26:36.053825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29654331bd83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('game_id', sa.String(length=128), nullable=False, comment='Human-readable game ID from GameRegistry'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False, comment='created | running | paused | finished | error'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Game rules, seed, max_turns, etc.'),
    sa.Column('winner_id', sa.Integer(), nullable=True, comment='Player ID of the winner (if any)'),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Additional metadata, tags, environment info'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_game_id'), 'games', ['game_id'], unique=True)
    op.create_index(op.f('ix_games_status'), 'games', ['status'], unique=False)
    op.create_table('game_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('game_uuid', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False, comment='Global sequence number across all events in this game (0, 1, 2, ...)'),
    sa.Column('turn_number', sa.Integer(), nullable=False, comment='Game turn when this event occurred'),
    sa.Column('event_type', sa.String(length=128), nullable=False, comment="e.g., 'turn_start', 'dice_roll', 'property_purchased', 'rent_paid'"),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full event data in JSON format'),
    sa.Column('actor_player_id', sa.Integer(), nullable=True, comment='Player ID who triggered this event (if applicable)'),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_uuid', 'sequence_number', name='uq_game_event_sequence')
    )
    op.create_index(op.f('ix_game_events_event_type'), 'game_events', ['event_type'], unique=False)
    op.create_index('ix_game_events_game_sequence', 'game_events', ['game_uuid', 'sequence_number'], unique=False)
    op.create_index('ix_game_events_game_turn', 'game_events', ['game_uuid', 'turn_number'], unique=False)
    op.create_index(op.f('ix_game_events_game_uuid'), 'game_events', ['game_uuid'], unique=False)
    op.create_index('ix_game_events_payload', 'game_events', ['payload'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_game_events_timestamp'), 'game_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_game_events_turn_number'), 'game_events', ['turn_number'], unique=False)
    op.create_index('ix_game_events_type_timestamp', 'game_events', ['event_type', 'timestamp'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('game_uuid', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False, comment='Player ID within the game (0, 1, 2, ...)'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=64), nullable=False, comment='greedy | random | human | llm'),
    sa.Column('final_cash', sa.Integer(), nullable=True),
    sa.Column('final_net_worth', sa.Integer(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('is_bankrupt', sa.Boolean(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=True, comment='1st, 2nd, 3rd, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_uuid', 'player_id', name='uq_game_player')
    )
    op.create_index('ix_players_game_player', 'players', ['game_uuid', 'player_id'], unique=False)
    op.create_index(op.f('ix_players_game_uuid'), 'players', ['game_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_game_uuid'), table_name='players')
    op.drop_index('ix_players_game_player', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_game_events_type_timestamp', table_name='game_events')
    op.drop_index(op.f('ix_game_events_turn_number'), table_name='game_events')
    op.drop_index(op.f('ix_game_events_timestamp'), table_name='game_events')
    op.drop_index('ix_game_events_payload', table_name='game_events', postgresql_using='gin')
    op.drop_index(op.f('ix_game_events_game_uuid'), table_name='game_events')
    op.drop_index('ix_game_events_game_turn', table_name='game_events')
    op.drop_index('ix_game_events_game_sequence', table_name='game_events')
    op.drop_index(op.f('ix_game_events_event_type'), table_name='game_events')
    op.drop_table('game_events')
    op.drop_index(op.f('ix_games_status'), table_name='games')
    op.drop_index(op.f('ix_games_game_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
