"""PR

Revision ID: 1bfdc6e41610
Revises: 29654331bd83
Create Date: 2025-12-16 17:16:50.738477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bfdc6e41610'
down_revision: Union[str, Sequence[str], None] = '29654331bd83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('game_uuid', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('game_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Complete game state snapshot when decision was made'),
    sa.Column('player_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Player state including cash, properties, cards, etc.'),
    sa.Column('available_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Actions available to the player at this point'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='Prompt sent to the LLM'),
    sa.Column('reasoning', sa.Text(), nullable=False, comment="LLM's reasoning process"),
    sa.Column('chosen_action', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Action chosen by the LLM'),
    sa.Column('strategy_description', sa.Text(), nullable=True, comment="LLM's description of its strategy"),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True, comment='Time taken to process the decision'),
    sa.Column('model_version', sa.String(length=128), nullable=True, comment='LLM model version used'),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_uuid', 'sequence_number', name='uq_llm_decision_sequence')
    )
    op.create_index('ix_llm_decisions_game_turn', 'llm_decisions', ['game_uuid', 'turn_number'], unique=False)
    op.create_index(op.f('ix_llm_decisions_game_uuid'), 'llm_decisions', ['game_uuid'], unique=False)
    op.create_index('ix_llm_decisions_player', 'llm_decisions', ['game_uuid', 'player_id'], unique=False)
    op.create_index('ix_llm_decisions_reasoning_text', 'llm_decisions', [sa.literal_column("to_tsvector('english', reasoning)")], unique=False, postgresql_using='gin')
    op.create_index('ix_llm_decisions_strategy_text', 'llm_decisions', [sa.literal_column("to_tsvector('english', strategy_description)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_llm_decisions_timestamp'), 'llm_decisions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_llm_decisions_turn_number'), 'llm_decisions', ['turn_number'], unique=False)
    op.add_column('players', sa.Column('llm_model_name', sa.String(length=128), nullable=True, comment='Name of the LLM model used by this player'))
    op.add_column('players', sa.Column('llm_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Parameters used for the LLM (temperature, etc.)'))
    op.add_column('players', sa.Column('llm_strategy_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Strategy profile of the LLM player'))
    op.add_column('players', sa.Column('llm_learning_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Accumulated learning data for this LLM player'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'llm_learning_data')
    op.drop_column('players', 'llm_strategy_profile')
    op.drop_column('players', 'llm_parameters')
    op.drop_column('players', 'llm_model_name')
    op.drop_index(op.f('ix_llm_decisions_turn_number'), table_name='llm_decisions')
    op.drop_index(op.f('ix_llm_decisions_timestamp'), table_name='llm_decisions')
    op.drop_index('ix_llm_decisions_strategy_text', table_name='llm_decisions', postgresql_using='gin')
    op.drop_index('ix_llm_decisions_reasoning_text', table_name='llm_decisions', postgresql_using='gin')
    op.drop_index('ix_llm_decisions_player', table_name='llm_decisions')
    op.drop_index(op.f('ix_llm_decisions_game_uuid'), table_name='llm_decisions')
    op.drop_index('ix_llm_decisions_game_turn', table_name='llm_decisions')
    op.drop_table('llm_decisions')
    # ### end Alembic commands ###
